# Dockerized Passivbot with PBGUI
# https://github.com/LeonSpors/passivbot-docker

services:
  passivbot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PB6_VERSION: v6.1.4b                                                         # Set the version of PB6
        PB7_VERSION: master                                                          # Set the version of PB7. Default is latest commit on main line
        PBGUI_VERSION: main
    environment:
      - USERDATA=${USERDATA}                                                          # Environment variable for user data directory
    restart: always
    volumes:
      # Make sure to create a .env file in the same directory
      # This file should define the USERDATA variable for volume mounting
      
      # PBGUI
      - ${USERDATA}/configs/secrets.toml:/app/pbgui/.streamlit/secrets.toml           # Required for PBGUI authentication
      - ${USERDATA}/configs/pbgui.ini:/app/pbgui/pbgui.ini                            # Required for PBGUI configuration
      - ${USERDATA}/pbgui:/app/pbgui/data                                             # Required for PBGUI data storage

      # Rclone
      # Optional volumes (comment if needed):
      #- ${USERDATA}/configs/rclone.conf:/root/.config/rclone/rclone.conf             # Uncomment to use Rclone for file transfers

      # Passivbot 6.X
      - ${USERDATA}/configs/api-keys.json:/app/pb6/api-keys.json                      # Required for API keys configuration
      - ${USERDATA}/historical_data:/app/pb6/historical_data                          # Historical data storage for PB6
      - ${USERDATA}/pb6/configs/:/app/pb6/configs                                     # Configurations for PB6
      - ${USERDATA}/pb6/backtests:/app/pb6/backtests                                  # Backtest results storage for PB6
      - ${USERDATA}/pb6/caches:/app/pb6/caches                                        # Caches for PB6
      - ${USERDATA}/pb6/optimize_results:/app/pb6/optimize_results                    # Optimization results for PB6
      - ${USERDATA}/pb6/optimize_results_analysis:/app/pb6/optimize_results_analysis  # Analysis of optimization results for PB6

      # Passivbot 7.X
      - ${USERDATA}/configs/api-keys.json:/app/pb7/api-keys.json                      # Required for API keys configuration
      - ${USERDATA}/historical_data:/app/pb7/historical_data                          # Historical data storage for PB7
      - ${USERDATA}/pb7/configs/:/app/pb7/configs                                     # Configurations for PB7
      - ${USERDATA}/pb7/backtests:/app/pb7/backtests                                  # Backtest results storage for PB7
      - ${USERDATA}/pb7/caches:/app/pb7/caches                                        # Caches for PB7
      - ${USERDATA}/pb7/optimize_results:/app/pb7/optimize_results                    # Optimization results for PB7
      - ${USERDATA}/pb7/optimize_results_analysis:/app/pb7/optimize_results_analysis  # Analysis of optimization results for PB7
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.gzip.compress=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.passivbot.entryPoints=http"
      - "traefik.http.routers.passivbot.middlewares=redirect-to-https"
      - "traefik.http.routers.passivbot.rule=Host(`https://trade-bot2.devfrontier.xyz/`) && PathPrefix(`/`)"
      - "traefik.http.routers.passivbot.service=http-0-a8gggkog48sg0wwkos0gwwgs"
      - "traefik.http.routers.passivbot.entryPoints=https"
      - "traefik.http.routers.passivbot.middlewares=gzip"
      - "traefik.http.routers.passivbot.rule=Host(`trade-bot2.devfrontier.xyz`)"
      - "traefik.http.services.passivbot.loadbalancer.server.port=8501"
      - "traefik.http.routers.passivbot.rule=Host(`trade-bot2.devfrontier.xyz`) && PathPrefix(`/`)"
      - "traefik.http.routers.passivbot.service=https-0-a8gggkog48sg0wwkos0gwwgs"
      - "traefik.http.routers.passivbot.tls.certresolver=letsencrypt"
      - "traefik.http.routers.passivbot.tls=true"
      - "traefik.http.services.passivbot.loadbalancer.server.port=8501"
      - "caddy_0.encode=zstd gzip"
      - "caddy_0.handle_path.0_reverse_proxy={{upstreams 8501}}"
      - "caddy_0.handle_path=/*"
      - "caddy_0.header=-Server"
      - "caddy_0=https://trade-bot2.devfrontier.xyz"
      - "caddy_ingress_network=coolify"

